---
default: &default
  cloud_name: <%= ENV["CLOUDINARY_NAME"] %>
  api_key: <%= ENV["CLOUDINARY_KEY"] %>
  api_secret: <%= ENV["CLOUDINARY_SECRET"] %>
development:
  <<: *default
staging:
  <<: *default
production:
  <<: *default